apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment
  labels:
    app: my-java-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-java-app
  template:
    metadata:
      labels:
        app: my-java-app
    spec:
      volumes:
      - name: persistent-data
        hostPath:
          # montando directorio local M:\ecr\kubernetes-java\test-data
          path: /mnt/m/ecr/kubernetes-java/test-data/
          type: Directory  
      containers:
      - name: my-java-container
        image: java-app:dev-local-rancher
        volumeMounts:
        - name: persistent-data
          mountPath: /var/lib/my-data/
        envFrom:
          - configMapRef:
              name: myconfigmap
          - secretRef:
              name: mysecret
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: 500M
            cpu: "500m"
        ports:
        - containerPort: 8080